version: "3.8"
services:
  rust_web_container:
    build:
      dockerfile: rust/Dockerfile
    container_name: rust_web_container
    tty: true
  postgres_container:
    container_name: postgres_container
    build: postgres
    restart: always
    ports:
      - "54321:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
volumes:
  postgres_volume: